name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish-nuget:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.303'

      - name: Restore Dependencies
        run: dotnet restore Bank/Bank.Domain/Bank.Domain.csproj

      - name: Build Project
        run: dotnet build Bank/Bank.Domain/Bank.Domain.csproj --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack Bank/Bank.Domain/Bank.Domain.csproj --configuration Release --output ./nupkg
      
      - name: Add GitHub NuGet Source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      
      - name: Push NuGet Package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
      
