name: Build and Publish NuGet Package

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-publish-nuget:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.303'

      - name: Restore Dependencies
        run: dotnet restore Bank/Bank.Domain/Bank.Domain.csproj

      - name: Build Project
        run: dotnet build Bank/Bank.Domain/Bank.Domain.csproj --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack Bank/Bank.Domain/Bank.Domain.csproj --configuration Release --output ./nupkg

      - name: Push NuGet Package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/nkmelndz/index.json"
