name: Crear Release y NuGet

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Generar tag dinámico
        id: generate_tag
        run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Obtener notas de los commits
        run: |
          echo "## Cambios en la versión ${{ env.TAG_NAME }}" > release_notes.md
          git log --pretty=format:"- %s" -n 10 >> release_notes.md

      - name: Crear nuevo tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Crear Release en GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          bodyFile: "release_notes.md"
          token: ${{ secrets.GH_TOKEN }}
          replacesArtifacts: true

      - name: Crear paquete NuGet
        run: |
          dotnet pack Bank/Bank.Domain/Bank.Domain.csproj -c Release \
            -p:PackageId=BankDomain.nkmelndz 

      - name: Verificar paquete generado
        run: ls -l Bank/Bank.Domain/bin/Release/

      - name: Publicar paquete en GitHub Packages
        run: |
          dotnet nuget push Bank/Bank.Domain/bin/Release/*.nupkg \
            --skip-duplicate \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GH_TOKEN }}
